default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>